// LOCALHOST

### get all contacts
GET http://127.0.0.1:8080/contacts HTTP/1.1

### get single contact
GET http://127.0.0.1:8080/contacts/68d8c0b2449b614205fec38b HTTP/1.1

### get single contact
GET http://127.0.0.1:8080/contacts/68d8c0d4449b614205fec38c HTTP/1.1

### get single contact
GET http://127.0.0.1:8080/contacts/68eaeef8121a031845a6d5a5 HTTP/1.1

### create new contact 
POST http://127.0.0.1:8080/contacts HTTP/1.1 
content-type: application/json

{
    "firstName": "Bob",
    "lastName": "Bobson",
    "email": "testEmail@mail.com",
    "favoriteColor": "purple",
    "birthday": "5/5/2005"
}

### update contact
PUT http://127.0.0.1:8080/contacts/68d8c0b2449b614205fec38b HTTP/1.1
Content-Type: application/json

{
    "firstName": "Alisha",
    "lastName": "Jeppesen",
    "email": "bestMom@gmail.com",
    "favoriteColor": "green",
    "birthday": "05/14/1975"
}

### delete contact
DELETE http://127.0.0.1:8080/contacts/68e19bb24fa745c14d3d10fb HTTP/1.1

// PRODUCTION

###
GET https://cse341jeppesen.onrender.com/contacts HTTP/1.1

###
GET https://cse341jeppesen.onrender.com/contacts/68d8c0b2449b614205fec38b HTTP/1.1

###
GET https://cse341jeppesen.onrender.com/contacts/68d8c0d4449b614205fec38c HTTP/1.1

###
GET https://cse341jeppesen.onrender.com/contacts/68d8c0de449b614205fec38d HTTP/1.1

### create new contact
POST https://cse341jeppesen.onrender.com/contacts/ HTTP/1.1 
content-type: application/json

{
    "firstName": "Bob",
    "lastName": "Bobson",
    "email": "testEmail@mail.com",
    "favoriteColor": "purple",
    "birthday": "5/5/2005"
}

### update contact
PUT https://cse341jeppesen.onrender.com/contacts/68d8c0b2449b614205fec38b HTTP/1.1
Content-Type: application/json

{
    "firstName": "Alisha",
    "lastName": "Jeppesen",
    "email": "bestMom@gmail.com",
    "favoriteColor": "blue",
    "birthday": "05/14/1975"
}

### delete contact
DELETE https://cse341jeppesen.onrender.com/contacts/68e19c1b83f70f0f5b7a3ce5 HTTP/1.1
